apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stilling-feed
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 40
  readiness:
    path: /internal/isReady
    initialDelay: 40
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - name: pam-stilling-feed
        type: POSTGRES_14
        diskType: SSD
        highAvailability: true
        diskSize: 50
        diskAutoresize: true
        tier: db-custom-2-7680
        databases:
          - name: pamstillingfeed
            envVarPrefix: DB
        cascadingDelete: false
  kafka:
    pool: {{kafka_pool}}
  envFrom:
    - secret: pam-stilling-feed-secret
  env:
    - name: STILLING_INTERN_TOPIC
      value: teampam.stilling-intern-1
    - name: STILLING_INTERN_GROUP_ID
      value: StillingFeed3
    - name: STILLING_URL_BASE
      value: "{{ stilling_url_base }}"
    - name: TILGANGSSTYRING_ENABLED
      value: "{{ tilgangsstyring_enabled }}"
    - name: REKJOR_DETALJER_ENABLED
      value: "{{ rekjor_detaljer_enabled }}"
    - name: REKJOR_DETALJER_GROUP_ID
      value: "{{ rekjor_detaljer_group_id }}"
